application: nippongrammar
version: 3
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: .*
  script: main.py

